// Generated file - SolidWorks invokes toolbar callbacks by method name, so every
// macro slot and every flyout needs a concrete method. Counts must match the
// MaxMacroCommands / MaxFlyouts constants.
namespace MacroDeck
{
    public partial class MacroDeckAddin
    {
        internal const int MaxMacroCommands = 250;
        internal const int MaxFlyouts = 100;

        public void RunMacro0() { RunMacroAt(0); }
        public void RunMacro1() { RunMacroAt(1); }
        public void RunMacro2() { RunMacroAt(2); }
        public void RunMacro3() { RunMacroAt(3); }
        public void RunMacro4() { RunMacroAt(4); }
        public void RunMacro5() { RunMacroAt(5); }
        public void RunMacro6() { RunMacroAt(6); }
        public void RunMacro7() { RunMacroAt(7); }
        public void RunMacro8() { RunMacroAt(8); }
        public void RunMacro9() { RunMacroAt(9); }
        public void RunMacro10() { RunMacroAt(10); }
        public void RunMacro11() { RunMacroAt(11); }
        public void RunMacro12() { RunMacroAt(12); }
        public void RunMacro13() { RunMacroAt(13); }
        public void RunMacro14() { RunMacroAt(14); }
        public void RunMacro15() { RunMacroAt(15); }
        public void RunMacro16() { RunMacroAt(16); }
        public void RunMacro17() { RunMacroAt(17); }
        public void RunMacro18() { RunMacroAt(18); }
        public void RunMacro19() { RunMacroAt(19); }
        public void RunMacro20() { RunMacroAt(20); }
        public void RunMacro21() { RunMacroAt(21); }
        public void RunMacro22() { RunMacroAt(22); }
        public void RunMacro23() { RunMacroAt(23); }
        public void RunMacro24() { RunMacroAt(24); }
        public void RunMacro25() { RunMacroAt(25); }
        public void RunMacro26() { RunMacroAt(26); }
        public void RunMacro27() { RunMacroAt(27); }
        public void RunMacro28() { RunMacroAt(28); }
        public void RunMacro29() { RunMacroAt(29); }
        public void RunMacro30() { RunMacroAt(30); }
        public void RunMacro31() { RunMacroAt(31); }
        public void RunMacro32() { RunMacroAt(32); }
        public void RunMacro33() { RunMacroAt(33); }
        public void RunMacro34() { RunMacroAt(34); }
        public void RunMacro35() { RunMacroAt(35); }
        public void RunMacro36() { RunMacroAt(36); }
        public void RunMacro37() { RunMacroAt(37); }
        public void RunMacro38() { RunMacroAt(38); }
        public void RunMacro39() { RunMacroAt(39); }
        public void RunMacro40() { RunMacroAt(40); }
        public void RunMacro41() { RunMacroAt(41); }
        public void RunMacro42() { RunMacroAt(42); }
        public void RunMacro43() { RunMacroAt(43); }
        public void RunMacro44() { RunMacroAt(44); }
        public void RunMacro45() { RunMacroAt(45); }
        public void RunMacro46() { RunMacroAt(46); }
        public void RunMacro47() { RunMacroAt(47); }
        public void RunMacro48() { RunMacroAt(48); }
        public void RunMacro49() { RunMacroAt(49); }
        public void RunMacro50() { RunMacroAt(50); }
        public void RunMacro51() { RunMacroAt(51); }
        public void RunMacro52() { RunMacroAt(52); }
        public void RunMacro53() { RunMacroAt(53); }
        public void RunMacro54() { RunMacroAt(54); }
        public void RunMacro55() { RunMacroAt(55); }
        public void RunMacro56() { RunMacroAt(56); }
        public void RunMacro57() { RunMacroAt(57); }
        public void RunMacro58() { RunMacroAt(58); }
        public void RunMacro59() { RunMacroAt(59); }
        public void RunMacro60() { RunMacroAt(60); }
        public void RunMacro61() { RunMacroAt(61); }
        public void RunMacro62() { RunMacroAt(62); }
        public void RunMacro63() { RunMacroAt(63); }
        public void RunMacro64() { RunMacroAt(64); }
        public void RunMacro65() { RunMacroAt(65); }
        public void RunMacro66() { RunMacroAt(66); }
        public void RunMacro67() { RunMacroAt(67); }
        public void RunMacro68() { RunMacroAt(68); }
        public void RunMacro69() { RunMacroAt(69); }
        public void RunMacro70() { RunMacroAt(70); }
        public void RunMacro71() { RunMacroAt(71); }
        public void RunMacro72() { RunMacroAt(72); }
        public void RunMacro73() { RunMacroAt(73); }
        public void RunMacro74() { RunMacroAt(74); }
        public void RunMacro75() { RunMacroAt(75); }
        public void RunMacro76() { RunMacroAt(76); }
        public void RunMacro77() { RunMacroAt(77); }
        public void RunMacro78() { RunMacroAt(78); }
        public void RunMacro79() { RunMacroAt(79); }
        public void RunMacro80() { RunMacroAt(80); }
        public void RunMacro81() { RunMacroAt(81); }
        public void RunMacro82() { RunMacroAt(82); }
        public void RunMacro83() { RunMacroAt(83); }
        public void RunMacro84() { RunMacroAt(84); }
        public void RunMacro85() { RunMacroAt(85); }
        public void RunMacro86() { RunMacroAt(86); }
        public void RunMacro87() { RunMacroAt(87); }
        public void RunMacro88() { RunMacroAt(88); }
        public void RunMacro89() { RunMacroAt(89); }
        public void RunMacro90() { RunMacroAt(90); }
        public void RunMacro91() { RunMacroAt(91); }
        public void RunMacro92() { RunMacroAt(92); }
        public void RunMacro93() { RunMacroAt(93); }
        public void RunMacro94() { RunMacroAt(94); }
        public void RunMacro95() { RunMacroAt(95); }
        public void RunMacro96() { RunMacroAt(96); }
        public void RunMacro97() { RunMacroAt(97); }
        public void RunMacro98() { RunMacroAt(98); }
        public void RunMacro99() { RunMacroAt(99); }
        public void RunMacro100() { RunMacroAt(100); }
        public void RunMacro101() { RunMacroAt(101); }
        public void RunMacro102() { RunMacroAt(102); }
        public void RunMacro103() { RunMacroAt(103); }
        public void RunMacro104() { RunMacroAt(104); }
        public void RunMacro105() { RunMacroAt(105); }
        public void RunMacro106() { RunMacroAt(106); }
        public void RunMacro107() { RunMacroAt(107); }
        public void RunMacro108() { RunMacroAt(108); }
        public void RunMacro109() { RunMacroAt(109); }
        public void RunMacro110() { RunMacroAt(110); }
        public void RunMacro111() { RunMacroAt(111); }
        public void RunMacro112() { RunMacroAt(112); }
        public void RunMacro113() { RunMacroAt(113); }
        public void RunMacro114() { RunMacroAt(114); }
        public void RunMacro115() { RunMacroAt(115); }
        public void RunMacro116() { RunMacroAt(116); }
        public void RunMacro117() { RunMacroAt(117); }
        public void RunMacro118() { RunMacroAt(118); }
        public void RunMacro119() { RunMacroAt(119); }
        public void RunMacro120() { RunMacroAt(120); }
        public void RunMacro121() { RunMacroAt(121); }
        public void RunMacro122() { RunMacroAt(122); }
        public void RunMacro123() { RunMacroAt(123); }
        public void RunMacro124() { RunMacroAt(124); }
        public void RunMacro125() { RunMacroAt(125); }
        public void RunMacro126() { RunMacroAt(126); }
        public void RunMacro127() { RunMacroAt(127); }
        public void RunMacro128() { RunMacroAt(128); }
        public void RunMacro129() { RunMacroAt(129); }
        public void RunMacro130() { RunMacroAt(130); }
        public void RunMacro131() { RunMacroAt(131); }
        public void RunMacro132() { RunMacroAt(132); }
        public void RunMacro133() { RunMacroAt(133); }
        public void RunMacro134() { RunMacroAt(134); }
        public void RunMacro135() { RunMacroAt(135); }
        public void RunMacro136() { RunMacroAt(136); }
        public void RunMacro137() { RunMacroAt(137); }
        public void RunMacro138() { RunMacroAt(138); }
        public void RunMacro139() { RunMacroAt(139); }
        public void RunMacro140() { RunMacroAt(140); }
        public void RunMacro141() { RunMacroAt(141); }
        public void RunMacro142() { RunMacroAt(142); }
        public void RunMacro143() { RunMacroAt(143); }
        public void RunMacro144() { RunMacroAt(144); }
        public void RunMacro145() { RunMacroAt(145); }
        public void RunMacro146() { RunMacroAt(146); }
        public void RunMacro147() { RunMacroAt(147); }
        public void RunMacro148() { RunMacroAt(148); }
        public void RunMacro149() { RunMacroAt(149); }
        public void RunMacro150() { RunMacroAt(150); }
        public void RunMacro151() { RunMacroAt(151); }
        public void RunMacro152() { RunMacroAt(152); }
        public void RunMacro153() { RunMacroAt(153); }
        public void RunMacro154() { RunMacroAt(154); }
        public void RunMacro155() { RunMacroAt(155); }
        public void RunMacro156() { RunMacroAt(156); }
        public void RunMacro157() { RunMacroAt(157); }
        public void RunMacro158() { RunMacroAt(158); }
        public void RunMacro159() { RunMacroAt(159); }
        public void RunMacro160() { RunMacroAt(160); }
        public void RunMacro161() { RunMacroAt(161); }
        public void RunMacro162() { RunMacroAt(162); }
        public void RunMacro163() { RunMacroAt(163); }
        public void RunMacro164() { RunMacroAt(164); }
        public void RunMacro165() { RunMacroAt(165); }
        public void RunMacro166() { RunMacroAt(166); }
        public void RunMacro167() { RunMacroAt(167); }
        public void RunMacro168() { RunMacroAt(168); }
        public void RunMacro169() { RunMacroAt(169); }
        public void RunMacro170() { RunMacroAt(170); }
        public void RunMacro171() { RunMacroAt(171); }
        public void RunMacro172() { RunMacroAt(172); }
        public void RunMacro173() { RunMacroAt(173); }
        public void RunMacro174() { RunMacroAt(174); }
        public void RunMacro175() { RunMacroAt(175); }
        public void RunMacro176() { RunMacroAt(176); }
        public void RunMacro177() { RunMacroAt(177); }
        public void RunMacro178() { RunMacroAt(178); }
        public void RunMacro179() { RunMacroAt(179); }
        public void RunMacro180() { RunMacroAt(180); }
        public void RunMacro181() { RunMacroAt(181); }
        public void RunMacro182() { RunMacroAt(182); }
        public void RunMacro183() { RunMacroAt(183); }
        public void RunMacro184() { RunMacroAt(184); }
        public void RunMacro185() { RunMacroAt(185); }
        public void RunMacro186() { RunMacroAt(186); }
        public void RunMacro187() { RunMacroAt(187); }
        public void RunMacro188() { RunMacroAt(188); }
        public void RunMacro189() { RunMacroAt(189); }
        public void RunMacro190() { RunMacroAt(190); }
        public void RunMacro191() { RunMacroAt(191); }
        public void RunMacro192() { RunMacroAt(192); }
        public void RunMacro193() { RunMacroAt(193); }
        public void RunMacro194() { RunMacroAt(194); }
        public void RunMacro195() { RunMacroAt(195); }
        public void RunMacro196() { RunMacroAt(196); }
        public void RunMacro197() { RunMacroAt(197); }
        public void RunMacro198() { RunMacroAt(198); }
        public void RunMacro199() { RunMacroAt(199); }
        public void RunMacro200() { RunMacroAt(200); }
        public void RunMacro201() { RunMacroAt(201); }
        public void RunMacro202() { RunMacroAt(202); }
        public void RunMacro203() { RunMacroAt(203); }
        public void RunMacro204() { RunMacroAt(204); }
        public void RunMacro205() { RunMacroAt(205); }
        public void RunMacro206() { RunMacroAt(206); }
        public void RunMacro207() { RunMacroAt(207); }
        public void RunMacro208() { RunMacroAt(208); }
        public void RunMacro209() { RunMacroAt(209); }
        public void RunMacro210() { RunMacroAt(210); }
        public void RunMacro211() { RunMacroAt(211); }
        public void RunMacro212() { RunMacroAt(212); }
        public void RunMacro213() { RunMacroAt(213); }
        public void RunMacro214() { RunMacroAt(214); }
        public void RunMacro215() { RunMacroAt(215); }
        public void RunMacro216() { RunMacroAt(216); }
        public void RunMacro217() { RunMacroAt(217); }
        public void RunMacro218() { RunMacroAt(218); }
        public void RunMacro219() { RunMacroAt(219); }
        public void RunMacro220() { RunMacroAt(220); }
        public void RunMacro221() { RunMacroAt(221); }
        public void RunMacro222() { RunMacroAt(222); }
        public void RunMacro223() { RunMacroAt(223); }
        public void RunMacro224() { RunMacroAt(224); }
        public void RunMacro225() { RunMacroAt(225); }
        public void RunMacro226() { RunMacroAt(226); }
        public void RunMacro227() { RunMacroAt(227); }
        public void RunMacro228() { RunMacroAt(228); }
        public void RunMacro229() { RunMacroAt(229); }
        public void RunMacro230() { RunMacroAt(230); }
        public void RunMacro231() { RunMacroAt(231); }
        public void RunMacro232() { RunMacroAt(232); }
        public void RunMacro233() { RunMacroAt(233); }
        public void RunMacro234() { RunMacroAt(234); }
        public void RunMacro235() { RunMacroAt(235); }
        public void RunMacro236() { RunMacroAt(236); }
        public void RunMacro237() { RunMacroAt(237); }
        public void RunMacro238() { RunMacroAt(238); }
        public void RunMacro239() { RunMacroAt(239); }
        public void RunMacro240() { RunMacroAt(240); }
        public void RunMacro241() { RunMacroAt(241); }
        public void RunMacro242() { RunMacroAt(242); }
        public void RunMacro243() { RunMacroAt(243); }
        public void RunMacro244() { RunMacroAt(244); }
        public void RunMacro245() { RunMacroAt(245); }
        public void RunMacro246() { RunMacroAt(246); }
        public void RunMacro247() { RunMacroAt(247); }
        public void RunMacro248() { RunMacroAt(248); }
        public void RunMacro249() { RunMacroAt(249); }

        public void FlyoutOpen0() { FlyoutOpenAt(0); }
        public void FlyoutOpen1() { FlyoutOpenAt(1); }
        public void FlyoutOpen2() { FlyoutOpenAt(2); }
        public void FlyoutOpen3() { FlyoutOpenAt(3); }
        public void FlyoutOpen4() { FlyoutOpenAt(4); }
        public void FlyoutOpen5() { FlyoutOpenAt(5); }
        public void FlyoutOpen6() { FlyoutOpenAt(6); }
        public void FlyoutOpen7() { FlyoutOpenAt(7); }
        public void FlyoutOpen8() { FlyoutOpenAt(8); }
        public void FlyoutOpen9() { FlyoutOpenAt(9); }
        public void FlyoutOpen10() { FlyoutOpenAt(10); }
        public void FlyoutOpen11() { FlyoutOpenAt(11); }
        public void FlyoutOpen12() { FlyoutOpenAt(12); }
        public void FlyoutOpen13() { FlyoutOpenAt(13); }
        public void FlyoutOpen14() { FlyoutOpenAt(14); }
        public void FlyoutOpen15() { FlyoutOpenAt(15); }
        public void FlyoutOpen16() { FlyoutOpenAt(16); }
        public void FlyoutOpen17() { FlyoutOpenAt(17); }
        public void FlyoutOpen18() { FlyoutOpenAt(18); }
        public void FlyoutOpen19() { FlyoutOpenAt(19); }
        public void FlyoutOpen20() { FlyoutOpenAt(20); }
        public void FlyoutOpen21() { FlyoutOpenAt(21); }
        public void FlyoutOpen22() { FlyoutOpenAt(22); }
        public void FlyoutOpen23() { FlyoutOpenAt(23); }
        public void FlyoutOpen24() { FlyoutOpenAt(24); }
        public void FlyoutOpen25() { FlyoutOpenAt(25); }
        public void FlyoutOpen26() { FlyoutOpenAt(26); }
        public void FlyoutOpen27() { FlyoutOpenAt(27); }
        public void FlyoutOpen28() { FlyoutOpenAt(28); }
        public void FlyoutOpen29() { FlyoutOpenAt(29); }
        public void FlyoutOpen30() { FlyoutOpenAt(30); }
        public void FlyoutOpen31() { FlyoutOpenAt(31); }
        public void FlyoutOpen32() { FlyoutOpenAt(32); }
        public void FlyoutOpen33() { FlyoutOpenAt(33); }
        public void FlyoutOpen34() { FlyoutOpenAt(34); }
        public void FlyoutOpen35() { FlyoutOpenAt(35); }
        public void FlyoutOpen36() { FlyoutOpenAt(36); }
        public void FlyoutOpen37() { FlyoutOpenAt(37); }
        public void FlyoutOpen38() { FlyoutOpenAt(38); }
        public void FlyoutOpen39() { FlyoutOpenAt(39); }
        public void FlyoutOpen40() { FlyoutOpenAt(40); }
        public void FlyoutOpen41() { FlyoutOpenAt(41); }
        public void FlyoutOpen42() { FlyoutOpenAt(42); }
        public void FlyoutOpen43() { FlyoutOpenAt(43); }
        public void FlyoutOpen44() { FlyoutOpenAt(44); }
        public void FlyoutOpen45() { FlyoutOpenAt(45); }
        public void FlyoutOpen46() { FlyoutOpenAt(46); }
        public void FlyoutOpen47() { FlyoutOpenAt(47); }
        public void FlyoutOpen48() { FlyoutOpenAt(48); }
        public void FlyoutOpen49() { FlyoutOpenAt(49); }
        public void FlyoutOpen50() { FlyoutOpenAt(50); }
        public void FlyoutOpen51() { FlyoutOpenAt(51); }
        public void FlyoutOpen52() { FlyoutOpenAt(52); }
        public void FlyoutOpen53() { FlyoutOpenAt(53); }
        public void FlyoutOpen54() { FlyoutOpenAt(54); }
        public void FlyoutOpen55() { FlyoutOpenAt(55); }
        public void FlyoutOpen56() { FlyoutOpenAt(56); }
        public void FlyoutOpen57() { FlyoutOpenAt(57); }
        public void FlyoutOpen58() { FlyoutOpenAt(58); }
        public void FlyoutOpen59() { FlyoutOpenAt(59); }
        public void FlyoutOpen60() { FlyoutOpenAt(60); }
        public void FlyoutOpen61() { FlyoutOpenAt(61); }
        public void FlyoutOpen62() { FlyoutOpenAt(62); }
        public void FlyoutOpen63() { FlyoutOpenAt(63); }
        public void FlyoutOpen64() { FlyoutOpenAt(64); }
        public void FlyoutOpen65() { FlyoutOpenAt(65); }
        public void FlyoutOpen66() { FlyoutOpenAt(66); }
        public void FlyoutOpen67() { FlyoutOpenAt(67); }
        public void FlyoutOpen68() { FlyoutOpenAt(68); }
        public void FlyoutOpen69() { FlyoutOpenAt(69); }
        public void FlyoutOpen70() { FlyoutOpenAt(70); }
        public void FlyoutOpen71() { FlyoutOpenAt(71); }
        public void FlyoutOpen72() { FlyoutOpenAt(72); }
        public void FlyoutOpen73() { FlyoutOpenAt(73); }
        public void FlyoutOpen74() { FlyoutOpenAt(74); }
        public void FlyoutOpen75() { FlyoutOpenAt(75); }
        public void FlyoutOpen76() { FlyoutOpenAt(76); }
        public void FlyoutOpen77() { FlyoutOpenAt(77); }
        public void FlyoutOpen78() { FlyoutOpenAt(78); }
        public void FlyoutOpen79() { FlyoutOpenAt(79); }
        public void FlyoutOpen80() { FlyoutOpenAt(80); }
        public void FlyoutOpen81() { FlyoutOpenAt(81); }
        public void FlyoutOpen82() { FlyoutOpenAt(82); }
        public void FlyoutOpen83() { FlyoutOpenAt(83); }
        public void FlyoutOpen84() { FlyoutOpenAt(84); }
        public void FlyoutOpen85() { FlyoutOpenAt(85); }
        public void FlyoutOpen86() { FlyoutOpenAt(86); }
        public void FlyoutOpen87() { FlyoutOpenAt(87); }
        public void FlyoutOpen88() { FlyoutOpenAt(88); }
        public void FlyoutOpen89() { FlyoutOpenAt(89); }
        public void FlyoutOpen90() { FlyoutOpenAt(90); }
        public void FlyoutOpen91() { FlyoutOpenAt(91); }
        public void FlyoutOpen92() { FlyoutOpenAt(92); }
        public void FlyoutOpen93() { FlyoutOpenAt(93); }
        public void FlyoutOpen94() { FlyoutOpenAt(94); }
        public void FlyoutOpen95() { FlyoutOpenAt(95); }
        public void FlyoutOpen96() { FlyoutOpenAt(96); }
        public void FlyoutOpen97() { FlyoutOpenAt(97); }
        public void FlyoutOpen98() { FlyoutOpenAt(98); }
        public void FlyoutOpen99() { FlyoutOpenAt(99); }
    }
}
